# Generated by Codex to align model with existing database column.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE accounts_user "
                        "ADD COLUMN IF NOT EXISTS is_email_verified boolean NOT NULL DEFAULT TRUE;"
                    ),
                    reverse_sql="ALTER TABLE accounts_user DROP COLUMN IF EXISTS is_email_verified;",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="user",
                    name="is_email_verified",
                    field=models.BooleanField(default=True),
                ),
            ],
        ),
    ]

