# Generated by Django 5.2.8 on 2025-12-23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_add_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PAYMENT_SUBMITTED', 'Payment Submitted'), ('KYC_SUBMITTED', 'KYC Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_PAYMENT', max_length=20),
        ),
        migrations.CreateModel(
            name='BusinessPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=18000, max_digits=10)),
                ('provider', models.CharField(default='Fonepay', max_length=100)),
                ('transaction_code', models.CharField(max_length=100)),
                ('screenshot', models.ImageField(upload_to='payments/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('business_name', models.CharField(max_length=255)),
                ('registration_pan', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('identity_type', models.CharField(max_length=100)),
                ('identity_number', models.CharField(max_length=255)),
                ('identity_document', models.FileField(upload_to='kyc_docs/')),
                ('payment_screenshot', models.FileField(blank=True, null=True, upload_to='kyc_payment/')),
                ('payment_transaction_code', models.CharField(blank=True, max_length=255, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kyc', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_kyc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
