# Generated by Django 5.2.8 on 2026-01-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_business_payment_and_kyc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='business_status',
            field=models.CharField(choices=[('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='UNDER_REVIEW', max_length=20),
        ),
    ]
