# Generated by Django 5.2.8 on 2026-01-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_business_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='business_status',
            field=models.CharField(choices=[('PAYMENT_PENDING', 'Payment Pending'), ('KYC_PENDING', 'KYC Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PAYMENT_PENDING', max_length=20),
        ),
    ]
