# Generated by Django 5.2.8 on 2026-01-04

import random
import string

from django.db import migrations, models


def generate_code():
    random_part = "".join(random.choices(string.ascii_uppercase + string.digits, k=6))
    return f"UDH-{random_part}"


def backfill_private_invite_codes(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    seen = set(User.objects.exclude(invite_code__isnull=True).exclude(invite_code="").values_list("invite_code", flat=True))

    def unique_code():
        code = generate_code()
        while code in seen or User.objects.filter(invite_code=code).exists():
            code = generate_code()
        return code

    for user in User.objects.filter(account_type="PRIVATE").order_by("id"):
        if user.invite_code and user.invite_code not in seen:
            seen.add(user.invite_code)
            continue
        code = unique_code()
        user.invite_code = code
        user.save(update_fields=["invite_code"])
        seen.add(code)

    # Clear invite_code for non-private accounts to keep uniqueness clean.
    User.objects.exclude(account_type="PRIVATE").update(invite_code=None)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_business_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="invite_code",
            field=models.CharField(
                db_index=True,
                max_length=10,
                unique=True,
                null=True,
                blank=True,
                editable=False,
            ),
        ),
        migrations.RunPython(backfill_private_invite_codes, migrations.RunPython.noop),
    ]
