# Generated by Django 5.2.8 on 2026-01-04 08:47

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_private_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(db_index=True, editable=False, max_length=10, unique=True, null=True, blank=True),
        ),
    ]
