# Generated by Django 5.2.8 on 2026-03-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_business_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
