# Generated by Django 5.2.8 on 2026-04-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_businessprofile_reminder_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, db_index=True, help_text='Google OAuth unique identifier', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_linked',
            field=models.BooleanField(default=False, help_text='Whether account is linked to Google'),
        ),
    ]
