# Generated by Django 5.2.8 on 2026-04-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_google_id_user_google_linked_user_phone_number'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE accounts_user "
                        "ADD COLUMN IF NOT EXISTS phone_number varchar(20) NULL;"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE accounts_user "
                        "ADD COLUMN IF NOT EXISTS two_factor_enabled boolean NOT NULL DEFAULT false;"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='user',
                    name='phone_number',
                    field=models.CharField(blank=True, help_text='Phone number with country code (e.g., 97798XXXXXXXX)', max_length=20, null=True),
                ),
                migrations.AddField(
                    model_name='user',
                    name='two_factor_enabled',
                    field=models.BooleanField(default=False, help_text='Whether 2FA is enabled for this user'),
                ),
            ],
        ),
    ]
