# Generated by Django 5.2.8 on 2026-05-03 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_two_factor_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactorotp',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='twofactorotp',
            name='purpose',
            field=models.CharField(choices=[('LOGIN_2FA', 'Login 2FA'), ('PASSWORD_RESET', 'Password Reset'), ('EMAIL_VERIFICATION', 'Email Verification')], db_index=True, default='LOGIN_2FA', max_length=20),
        ),
        migrations.AlterField(
            model_name='twofactorotp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_otps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='twofactorotp',
            index=models.Index(fields=['email', 'purpose'], name='accounts_tw_email_00e98e_idx'),
        ),
    ]
