# Generated by Django 5.2.8 on 2026-01-04 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0002_privatemoneytransaction'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='privatemoneytransaction',
            new_name='private_pri_owner_i_3ae8e3_idx',
            old_name='private_mon_owner_i_6f9b2f_idx',
        ),
    ]
