# Generated by Django 5.2.8 on 2026-01-11 09:05

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0003_rename_private_mon_owner_i_6f9b2f_idx_private_pri_owner_i_3ae8e3_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemoneytransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddConstraint(
            model_name='privatemoneytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='private_money_amount_gt_zero'),
        ),
    ]
