# Generated by Django 5.2.8 on 2026-03-08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        ("private", "0007_chatthread_chatmessage_chatparticipant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="related_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="core.transaction",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_private_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="private.privatemoneytransaction",
            ),
        ),
    ]
