# Generated by Django 5.2.8 on 2026-03-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_related_private_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SETTLEMENT', 'Settlement'), ('ACTIVITY', 'Activity')], max_length=30),
        ),
    ]
