# Generated by Django 5.2.8 on 2026-03-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="settled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
