# Generated by Django 5.2.8 on 2026-03-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_payment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='creditsale',
            new_name='core_credit_busines_ca8984_idx',
            old_name='core_credit_business_1a2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='creditsale',
            new_name='core_credit_custome_c872a0_idx',
            old_name='core_credit_customer_2d3e4f_idx',
        ),
        migrations.RenameIndex(
            model_name='creditsale',
            new_name='core_credit_status_5485e6_idx',
            old_name='core_credit_status_3e4f5g_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='core_paymen_busines_306ae2_idx',
            old_name='core_payment_business_5f6g7h_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='core_paymen_custome_7d25e0_idx',
            old_name='core_payment_customer_6g7h8i_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='core_paymen_credit__239381_idx',
            old_name='core_payment_credit_7h8i9j_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='core_produc_busines_8901ea_idx',
            old_name='core_produ_business_2cb0b0_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='core_produc_busines_5bd59b_idx',
            old_name='core_produ_business_4f16b1_idx',
        ),
        migrations.AlterField(
            model_name='creditsale',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='creditsaleitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
