# Generated by Django 5.2.8 on 2026-04-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_paymentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='checkout_url',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
