# Generated by Django 5.2.8 on 2026-01-21 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0004_constraints'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='businesstransaction',
            new_name='ocr_busines_owner_i_fabfaf_idx',
            old_name='businesstra_owner_tr_idx',
        ),
        migrations.RenameIndex(
            model_name='ocrdocument',
            new_name='ocr_ocrdocu_owner_i_a8a588_idx',
            old_name='ocr_doc_own_status_idx',
        ),
        migrations.RenameIndex(
            model_name='ocrdocument',
            new_name='ocr_ocrdocu_owner_i_69eab9_idx',
            old_name='ocr_doc_own_created_idx',
        ),
    ]
