# Generated by Django 5.2.8 on 2026-01-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0008_update_transaction_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstransaction',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
